### ISSUE TITLE
No MITMf...

### ISSUE THREAD

**Issue by ekkimosi** [H0nus/RogueSploit#5] opened 2017-06-10 19:15 UTC
Firstly, great work!
I installed RS root/Roguesploit and tried also root/prog/RogueSploit. 
So, each time I start RogueSploit ask me to install MITMf, choosing Yes and when exit terminal write that etc/mitmf/mitmf.conf not found...
Second question; my wireless interface is Wlan0 but I need to choose after few seconds 1 for many, many times.

**Comment by ekkimosi** [comment] 2017-06-10 19:22
![img_8904](https://user-images.githubusercontent.com/22117676/27005654-e2871ae0-4e22-11e7-9826-f2a76d76f5b5.JPG)
![img_8905](https://user-images.githubusercontent.com/22117676/27005655-e287a10e-4e22-11e7-8385-8e258e5692e9.JPG)

**Comment by B4ckP0r7** [comment] 2017-06-11 08:05
ok, so, mitmf changed configuration directory and now it’s mitmf same directory under config;
do you have installed hostapd ? that’s why maybe it’s not working; if your interface is wlan0, pay attention to write it good, because if you write Wlan0 will make the script no work; today i’ll work on that! Thanks for the patience:)

**Comment by ekkimosi** [comment] 2017-06-11 21:53
For Mitm I will clone and install in /etc. 
Hostapd it' installed. 
wlan0 it's typed in right way. 
Thank you for fast response.

**Comment by B4ckP0r7** [comment] 2017-06-12 09:54
ok, so now i'll update the git.
Please remove totally Mitmf, and try to install from kali's repos and let me know.
if it work, you can leave it;
if not, please try to use the installer, because now i just update the position of mitmf config.
If any others bugs/problem just let me know :)

**Comment by ekkimosi** [comment] 2017-06-12 09:57
Ok. I will uninstall MITMf completely and reinstall from apt-get.
We keep in touch.

**Comment by B4ckP0r7** [comment] 2017-06-12 10:05
ok, try now, i have updated it! let me know :)
i just want to know that at the moment mitmf isn't used, because it create problems with MSF Dnspoof, so i need to work on it! :)
I'm thinking to add a little python script to make dns spoof directly.
And again, MITMT (or any other Mitm frameworks) will not work for no dns response!
Sorry for the problems!

**Comment by ekkimosi** [comment] 2017-06-12 11:49
So, mitmf error solved but on first start works fine. If I shut off and restart RS, give me the starting Rogue accespoint loop like first photo. 
I need to reboot kali to work again.

**Comment by B4ckP0r7** [comment] 2017-06-12 12:24
mmh, can you make a video ? and please can you enable the logging?
for logging, edit the start of RogueSploit script like this:
===================================================
#DEBUG ONLY FOR LOGGIN, BREAK CTRL_C TRAP!!!#
#ENABLE IF YOU GET ERRORS; DO THE SAME FOR BEEFSTARTER SCRIPT AND OTHERS SCRIPTS TOO (not the .rc)
#DATE=$(date)
#echo $DATE
#LOG_FILE=$PWD/roguesploit.log
#exec > >(tee -a ${LOG_FILE} )
#exec 2> >(tee -a ${LOG_FILE} >&2)
#echo $DATE > $PWD/roguesploit.log
#echo -e $white"Logging Enabled, "$yellow"CTRL"$white"+"$red"C"$white" will not work!!"$transparent
#sleep 1

TO:

#DEBUG ONLY FOR LOGGIN, BREAK CTRL_C TRAP!!!#
#ENABLE IF YOU GET ERRORS; DO THE SAME FOR BEEFSTARTER SCRIPT AND OTHERS SCRIPTS TOO (not the .rc)
DATE=$(date)
echo $DATE
LOG_FILE=$PWD/roguesploit.log
exec > >(tee -a ${LOG_FILE} )
exec 2> >(tee -a ${LOG_FILE} >&2)
echo $DATE > $PWD/roguesploit.log
echo -e $white"Logging Enabled, "$yellow"CTRL"$white"+"$red"C"$white" will not work!!"$transparent
sleep 1

**Comment by B4ckP0r7** [comment] 2017-06-12 12:25
and pay attention, this logging will break ctrl_c function, so after you get the log file, disable it back and upload log somewhere or paste it here! 👍

**Comment by ekkimosi** [comment] 2017-06-12 14:53
`lun 12 giu 2017, 16.48.43, CEST
[1;37mLogging Enabled, [1;33mCTRL[1;37m+[1;31mC[1;37m will not work!![0m
[1;37m [!] RUNNING SERVICES [!]

[1;37mChecking Metasploit.....[0m[1;32mOK![0m
[1;37mChecking Hostapd.....[0m[1;32mOK![0m
[1;37mChecking DHCPD Server.....[0m[1;32mOK![0m
[1;37mChecking Python.....[0m[1;32mOK![0m
[1;37mChecking Beef.....[0m[1;32mOK![0m
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[3J[H[2J[1;34m[[1;33m?[1;34m] [1;33mDo you want to correctly install MITMF? (y/n)[1;34m[[1;33m*[1;34m][1;33mmitmf[1;37m@[1;31minstall[1;37m
RogueSploit: riga 43: [: troppi argomenti
RogueSploit: riga 63: mitmfconf: comando non trovato
[3J[H[2J[1;33m--<[1;34m[*][1;33m Welcome test, this is Roguesploit v0.5 -- by _B4ckp0r7 [1;34m[*][1;33m>--
[1;32m--<[?] What do you want to do? [?]>-- 
[1;32m       1. Start RogueAP
[1;32m       2. Start Pwning Services
[1;32m       3. Credits
[1;32m       4. Exit
[1;32m       5. TUTORIAL
[1;33m       6. Update wit Git
[1;31m[[1;33mtest[1;31m@[1;33mroguesploit[1;31m][1;33m: [1;33mStarting RogueAP
[1;31m[!][1;33m Input the name you want to use for the Access Point [1;31m[!]
[1;31m[[1;33mtest[1;31m@[1;33mfakeap[1;31m][1;37m: [1;31m([1;37m Ex. AndroidAP[1;31m ) Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[1;31m[!] test YOU NEED wlan0 INTERFACE FOR THESE [!]
[1;33mStarting RogueAP on wlan0 with name AndroidAP
8888888b.                                                        888          d8b 888           .d88888b.  888b    888
888   Y88b                                                       888          Y8P 888          d88P" "Y88b 8888b   888
888    888                                                       888              888          888     888 88888b  888
888   d88P  .d88b.   .d88b.  888  888  .d88b.  .d8888b  88888b.  888  .d88b.  888 888888       888     888 888Y88b 888
8888888P"  d88""88b d88P"88b 888  888 d8P  Y8b 88K      888 "88b 888 d88""88b 888 888          888     888 888 Y88b888
888 T88b   888  888 888  888 888  888 88888888 "Y8888b. 888  888 888 888  888 888 888          888     888 888  Y88888
888  T88b  Y88..88P Y88b 888 Y88b 888 Y8b.          X88 888 d88P 888 Y88..88P 888 Y88b.        Y88b. .d88P 888   Y8888
888   T88b  "Y88P"   "Y88888  "Y88888  "Y8888   88888P' 88888P"  888  "Y88P"  888  "Y888        "Y88888P"  888    Y888
                         888                            888
                    Y8b d88P                            888
                     "Y88P"                             888
[1;33m--<[1;34m[*][1;33m Welcome test, this is Roguesploit v0.5 -- by _B4ckp0r7 [1;34m[*][1;33m>--
[1;32m--<[?] What do you want to do? [?]>-- 
[1;32m       1. Start RogueAP
[1;32m       2. Start Pwning Services
[1;32m       3. Credits
[1;32m       4. Exit
[1;32m       5. TUTORIAL
[1;33m       6. Update wit Git
[1;31m[[1;33mtest[1;31m@[1;33mroguesploit[1;31m][1;33m: [1;33mStarting RogueAP
[1;31m[!][1;33m Input the name you want to use for the Access Point [1;31m[!]
[1;31m[[1;33mtest[1;31m@[1;33mfakeap[1;31m][1;37m: [1;31m([1;37m Ex. AndroidAP[1;31m ) Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[1;31m[!] test YOU NEED wlan0 INTERFACE FOR THESE [!]
[1;33mStarting RogueAP on wlan0 with name AndroidAP
8888888b.                                                        888          d8b 888           .d88888b.  888b    888
888   Y88b                                                       888          Y8P 888          d88P" "Y88b 8888b   888
888    888                                                       888              888          888     888 88888b  888
888   d88P  .d88b.   .d88b.  888  888  .d88b.  .d8888b  88888b.  888  .d88b.  888 888888       888     888 888Y88b 888
8888888P"  d88""88b d88P"88b 888  888 d8P  Y8b 88K      888 "88b 888 d88""88b 888 888          888     888 888 Y88b888
888 T88b   888  888 888  888 888  888 88888888 "Y8888b. 888  888 888 888  888 888 888          888     888 888  Y88888
888  T88b  Y88..88P Y88b 888 Y88b 888 Y8b.          X88 888 d88P 888 Y88..88P 888 Y88b.        Y88b. .d88P 888   Y8888
888   T88b  "Y88P"   "Y88888  "Y88888  "Y8888   88888P' 88888P"  888  "Y88P"  888  "Y888        "Y88888P"  888    Y888
                         888                            888
                    Y8b d88P                            888
                     "Y88P"                             888
[3J[H[2J[1;33m--<[1;34m[*][1;33m Welcome test, this is Roguesploit v0.5 -- by _B4ckp0r7 [1;34m[*][1;33m>--
[1;32m--<[?] What do you want to do? [?]>-- 
[1;32m       1. Start RogueAP
[1;32m       2. Start Pwning Services
[1;32m       3. Credits
[1;32m       4. Exit
[1;32m       5. TUTORIAL
[1;33m       6. Update wit Git
[1;31m[[1;33mtest[1;31m@[1;33mroguesploit[1;31m][1;33m: [1;31m[!!] This update will delete everything in this directory, continue anyway? [y/N] (B[m[1;31m[!!] Update aborted! Returning main menu in 3 secs [!!]
[1;33m--<[1;34m[*][1;33m Welcome test, this is Roguesploit v0.5 -- by _B4ckp0r7 [1;34m[*][1;33m>--
[1;32m--<[?] What do you want to do? [?]>-- 
[1;32m       1. Start RogueAP
[1;32m       2. Start Pwning Services
[1;32m       3. Credits
[1;32m       4. Exit
[1;32m       5. TUTORIAL
[1;33m       6. Update wit Git
[1;31m[[1;33mtest[1;31m@[1;33mroguesploit[1;31m][1;33m: [1;33mStarting RogueAP
[1;31m[!][1;33m Input the name you want to use for the Access Point [1;31m[!]
[1;31m[[1;33mtest[1;31m@[1;33mfakeap[1;31m][1;37m: [1;31m([1;37m Ex. AndroidAP[1;31m ) Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[1;31m[!] test YOU NEED wlan0 INTERFACE FOR THESE [!]
[1;33mStarting RogueAP on wlan0 with name TEST
8888888b.                                                        888          d8b 888           .d88888b.  888b    888
888   Y88b                                                       888          Y8P 888          d88P" "Y88b 8888b   888
888    888                                                       888              888          888     888 88888b  888
888   d88P  .d88b.   .d88b.  888  888  .d88b.  .d8888b  88888b.  888  .d88b.  888 888888       888     888 888Y88b 888
8888888P"  d88""88b d88P"88b 888  888 d8P  Y8b 88K      888 "88b 888 d88""88b 888 888          888     888 888 Y88b888
888 T88b   888  888 888  888 888  888 88888888 "Y8888b. 888  888 888 888  888 888 888          888     888 888  Y88888
888  T88b  Y88..88P Y88b 888 Y88b 888 Y8b.          X88 888 d88P 888 Y88..88P 888 Y88b.        Y88b. .d88P 888   Y8888
888   T88b  "Y88P"   "Y88888  "Y88888  "Y8888   88888P' 88888P"  888  "Y88P"  888  "Y888        "Y88888P"  888    Y888
                         888                            888
                    Y8b d88P                            888
                     "Y88P"                             888
[3J[H[2J[1;33m--<[1;34m[*][1;33m Welcome test, this is Roguesploit v0.5 -- by _B4ckp0r7 [1;34m[*][1;33m>--
[1;32m--<[?] What do you want to do? [?]>-- 
[1;32m       1. Start RogueAP
[1;32m       2. Start Pwning Services
[1;32m       3. Credits
[1;32m       4. Exit
[1;32m       5. TUTORIAL
[1;33m       6. Update wit Git
[1;31m[[1;33mtest[1;31m@[1;33mroguesploit[1;31m][1;33m: `

**Comment by ekkimosi** [comment] 2017-06-12 15:01
[https://vimeo.com/221279013](url)

**Comment by H0nus** [comment] 2017-06-12 15:17
Just saw the video, and this is strange;
when you shutdown the 2nd terminal, don't CTRL+C in the first, but please try to close manually the hostapd xterm, and after exit;
that's because maybe if you shutdown service like this, hostapd maybe say as deamon.
What os are you using? Debian? Ubuntu? maybe a Debian's distro?
If problems still rising, try in 2nd fake ap to use another name.
Waiting for news :)

**Comment by ekkimosi** [comment] 2017-06-12 15:21
Kali 2017.1 and I will try later as you say.

**Comment by H0nus** [comment] 2017-06-12 15:35
"zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18: undefined symbol: _ZN3JSC3DFE30performOSRAvailabilityAnalysisERNS0_5GraphE"
That's not an error about RogueSploit or some, it's an error of new zenity, and maybe it's not compatible with old releases.
If you want to use a distro like Kali, you should use Parrot Security OS, because it's more stable and with much more interestings tools and things, and it's made by Italian.
Btw, the error seems to be "unique" because i tried it on ParrotOS and it's working;
Need to fix the 3rd modules for little bugs;
Let me know

**Comment by ekkimosi** [comment] 2017-06-12 15:39
So, purged and reinstalled zenity. After reboot works fine. 
I will try later your fix

**Comment by H0nus** [comment] 2017-06-12 15:47
Did the ap problems fix?
if yes i'll close the issue :)
Happy to helped you out!

**Comment by ekkimosi** [comment] 2017-06-12 20:52
> **when you shutdown the 2nd terminal, don't CTRL+C in the first, but please try to close manually the hostapd xterm, and after exit;** 
that's because maybe if you shutdown service like this, hostapd maybe say as deamon.
**If problems still rising, try in 2nd fake ap to use another name**.
> 

I tried both but works only on first start... then I need to reboot Kali.

**Comment by H0nus** [comment] 2017-06-15 07:28
ant news?

**Comment by ekkimosi** [comment] 2017-06-15 07:42
No news. Same problem; need to restart.

**Comment by H0nus** [comment] 2017-06-25 16:16
closing due to a problem not caused by my script;
i’ll check on different distros/os.

**Closed by H0nus** 2017-06-25 16:16 UTC
Labels: enhancement
